services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  _instanceof:
    Waffle\Model\Config\ConfigItemInterface:
      tags: ['config_items']
    Waffle\Command\DiscoverableCommandInterface:
      tags: ['commands']
    Waffle\Command\DiscoverableTaskInterface:
      tags: ['tasks']
    Waffle\Command\DiscoverableRecipeInterface:
      tags: ['recipes']

  Waffle\:
    resource: '../src'

  Waffle\Application:
    public: true

  Waffle\Model\IO\IOStyle:
    public: true

  Waffle\Model\Config\ConfigTreeService:
    arguments:
      - !tagged config_items

  Waffle\Model\Command\CommandManager:
    arguments:
      - !tagged commands

  Waffle\Model\Command\TaskManager:
    arguments:
      - '@Waffle\Model\Context\Context'
      - '@Waffle\Model\Command\TaskFactory'
      - !tagged tasks

  Waffle\Model\Command\RecipeManager:
    arguments:
      - '@Waffle\Model\Context\Context'
      - '@Waffle\Model\Command\RecipeFactory'
      - !tagged recipes

  # The following services get tagged as service subscribers because they either
  # need to load an unknown service or they need to load a heavy service. Each
  # of these subscribe to the specific services that they need acces to in the
  # PHP code.
  Waffle\Model\Build\BackendBuildHandlerFactory:
    tags:
      - { name: 'container.service_subscriber'}

  Waffle\Model\Build\FrontendBuildHandlerFactory:
    tags:
      - { name: 'container.service_subscriber'}
